// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: inventory.sql

package pgstore

import (
	"context"
)

const getStockForProductID = `-- name: GetStockForProductID :one
SELECT stock FROM inventory WHERE product_id = $1
`

func (q *Queries) GetStockForProductID(ctx context.Context, productID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getStockForProductID, productID)
	var stock int64
	err := row.Scan(&stock)
	return stock, err
}

const setProductInventory = `-- name: SetProductInventory :exec
INSERT INTO inventory(product_id, stock) VALUES ($1, $2)
`

type SetProductInventoryParams struct {
	ProductID int64 `json:"product_id"`
	Stock     int64 `json:"stock"`
}

func (q *Queries) SetProductInventory(ctx context.Context, arg SetProductInventoryParams) error {
	_, err := q.db.ExecContext(ctx, setProductInventory, arg.ProductID, arg.Stock)
	return err
}

const updateProductInventory = `-- name: UpdateProductInventory :exec
UPDATE "inventory" SET stock = $1 WHERE product_id = $2
`

type UpdateProductInventoryParams struct {
	Stock     int64 `json:"stock"`
	ProductID int64 `json:"product_id"`
}

func (q *Queries) UpdateProductInventory(ctx context.Context, arg UpdateProductInventoryParams) error {
	_, err := q.db.ExecContext(ctx, updateProductInventory, arg.Stock, arg.ProductID)
	return err
}
