// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package pgstore

type Inventory struct {
	ID        int64 `json:"id"`
	ProductID int64 `json:"product_id"`
	Stock     int64 `json:"stock"`
}

type Order struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

type OrderItem struct {
	ID        int64 `json:"id"`
	OrderID   int64 `json:"order_id"`
	ProductID int64 `json:"product_id"`
	Quantity  int64 `json:"quantity"`
}

type Product struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Price int64  `json:"price"`
}

type User struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type UserProfile struct {
	ID       int64  `json:"id"`
	Category string `json:"category"`
	UserID   int64  `json:"user_id"`
	WalletID int64  `json:"wallet_id"`
}

type Wallet struct {
	ID      int64 `json:"id"`
	UserID  int64 `json:"user_id"`
	Balance int64 `json:"balance"`
}
