// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: order.sql

package pgstore

import (
	"context"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO "orders"(user_id) VALUES ($1) RETURNING id
`

func (q *Queries) CreateOrder(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, createOrder, userID)
	var id int64
	err := row.Scan(&id)
	return id, err
}
