// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: order_items.sql

package pgstore

import (
	"context"
)

const createOrderItem = `-- name: CreateOrderItem :exec
INSERT INTO "order_items" (order_id, product_id, quantity) VALUES ($1, $2, $3)
`

type CreateOrderItemParams struct {
	OrderID   int64 `json:"order_id"`
	ProductID int64 `json:"product_id"`
	Quantity  int64 `json:"quantity"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error {
	_, err := q.db.ExecContext(ctx, createOrderItem, arg.OrderID, arg.ProductID, arg.Quantity)
	return err
}
