// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: products.sql

package pgstore

import (
	"context"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products(name, price) VALUES ($1, $2) RETURNING id
`

type CreateProductParams struct {
	Name  string `json:"name"`
	Price int64  `json:"price"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createProduct, arg.Name, arg.Price)
	var id int64
	err := row.Scan(&id)
	return id, err
}
