// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: profile.sql

package pgstore

import (
	"context"
)

const createProfile = `-- name: CreateProfile :exec
INSERT INTO "user_profile"(user_id, wallet_id, category) VALUES ($1, $2, $3)
`

type CreateProfileParams struct {
	UserID   int64  `json:"user_id"`
	WalletID int64  `json:"wallet_id"`
	Category string `json:"category"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) error {
	_, err := q.db.ExecContext(ctx, createProfile, arg.UserID, arg.WalletID, arg.Category)
	return err
}
