// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package pgstore

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users(name) VALUES ($1) RETURNING id
`

func (q *Queries) CreateUser(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, createUser, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}
