// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: wallets.sql

package pgstore

import (
	"context"
)

const createWallet = `-- name: CreateWallet :one
INSERT INTO wallets(user_id, balance) VALUES ($1, $2) RETURNING id
`

type CreateWalletParams struct {
	UserID  int64 `json:"user_id"`
	Balance int64 `json:"balance"`
}

func (q *Queries) CreateWallet(ctx context.Context, arg CreateWalletParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createWallet, arg.UserID, arg.Balance)
	var id int64
	err := row.Scan(&id)
	return id, err
}
